export const SET_PAGEDATA = 'SET_PAGEDATA'
export const SET_FILTERDATA = 'SET_FILTERDATA'


export const CHANGE_ACTIVE_PAGE = 'CHANGE_ACTIVE_PAGE'
export const CHANGE_TOTAL_COUNT = 'CHANGE_TOTAL_COUNT'
export const CHANGE_PAGE_ARR = 'CHANGE_PAGE_ARR'
export const CLEAR_PAGE_ARR = 'CLEAR_PAGE_ARR'
export const SET_ALLDATA = 'SET_ALLDATA'


export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'
